# Generated by Django 5.2.6 on 2025-09-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='monthly_bill',
            new_name='monthlyBill',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quoterequest',
            old_name='rooftop_area',
            new_name='rooftopArea',
        ),
    ]
