# Generated by Django 5.2.4 on 2025-10-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarapp', '0002_rename_monthly_bill_quoterequest_monthlybill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quoterequest',
            old_name='city',
            new_name='district',
        ),
    ]
